// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


// app/layout.tsx
import { Fraunces, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero/Hero";
import Intro from "@/components/Intro";
import Collections from "@/components/Collections";
import Bespoke from "@/components/Bespoke";
import Quote from "@/components/Quote";
import ContactFooter from "@/components/Footer";
import Gallery from "@/components/Gallery";
import Milestones from "@/components/Milestones";

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-fraunces",
});
const inter = Inter({ subsets: ["latin"], weight: ["400", "500"], variable: "--font-inter" });

export const metadata = {
  title: "Heaven Furniture Mart — Designed. Crafted. Customized.",
  description: "Bespoke furniture and interior styling from Chattogram, Bangladesh.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${fraunces.variable} ${inter.variable} font-sans bg-ivory text-brown`}>
        <Navbar></Navbar>
        <Hero></Hero>
        <Intro></Intro>
        <Collections></Collections>
        <Bespoke></Bespoke>
        <Quote></Quote>
        <Gallery></Gallery>
        <Milestones></Milestones>
        {children}
        <ContactFooter></ContactFooter>
  
      </body>
    </html>
  );
}
